// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionGestionUniversitaire.Infrastructure;

#nullable disable

namespace SolutionGestionUniversitaire.Infrastructure.Migrations
{
    [DbContext(typeof(SolutionGestionUniversitaireContext))]
    partial class SolutionGestionUniversitaireContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionGestionUniversitaire.Core.Entities.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProfesseurId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesseurId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("SolutionGestionUniversitaire.Core.Entities.Professeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professeurs");
                });

            modelBuilder.Entity("SolutionGestionUniversitaire.Core.Entities.Cours", b =>
                {
                    b.HasOne("SolutionGestionUniversitaire.Core.Entities.Professeur", null)
                        .WithMany("CoursEnseignés")
                        .HasForeignKey("ProfesseurId");
                });

            modelBuilder.Entity("SolutionGestionUniversitaire.Core.Entities.Professeur", b =>
                {
                    b.Navigation("CoursEnseignés");
                });
#pragma warning restore 612, 618
        }
    }
}
